name: i_manager
description: A Flutter package that helps to manage widget states.
version: 1.0.0
# author:
homepage: https://github.com/kamalsayed98/i_manager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.25.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
